### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import 

### ISSUE THREAD

**Issue by chbw818** [dingsheng-ong/ipr-gan#10]
Hi!
when I try to run this code, I met this error and i found no solution on the Internet
`python train.py -c ./configs/DCGAN/baselines/dcgan-cifar10-c.yaml`
and my python=3.8.8,torch=1.8.0
and i tried many versions of numpy,but it didn't work
it seems that pdqhash caused this error
```
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    import experiments
  File "/root/autodl-tmp/ipr-gan/experiments/__init__.py", line 2, in <module>
    from experiments.image_generation import ImageGeneration
  File "/root/autodl-tmp/ipr-gan/experiments/image_generation.py", line 11, in <module>
    import models
  File "/root/autodl-tmp/ipr-gan/models/__init__.py", line 6, in <module>
    from models.wrappers import BlackBoxWrapper, WhiteBoxWrapper
  File "/root/autodl-tmp/ipr-gan/models/wrappers.py", line 4, in <module>
    import tools
  File "/root/autodl-tmp/ipr-gan/tools/__init__.py", line 4, in <module>
    from tools.phash_pvalue import compute_matching_prob
  File "/root/autodl-tmp/ipr-gan/tools/phash_pvalue.py", line 4, in <module>
    import pdqhash
  File "/root/miniconda3/envs/gan/lib/python3.8/site-packages/pdqhash/__init__.py", line 1, in <module>
    from .bindings import compute, compute_dihedral, compute_float
  File "pdqhash/bindings.pyx", line 1, in init pdqhash.bindings
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

**Comment by chbw818** [comment]
I managed to solve this problem by using numpy≥2.0 with suitable pytorch and pdqhash==2.7
