### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by crisjade** [dingsheng-ong/ipr-gan#3]
When run"attack_dcgan"
RuntimeError: Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "network.1.bitmask", "network.4.bitmask", "network.7.bitmask".
Traceback (most recent call last):
  File "C:/Users/DELL/Downloads/ipr-gan-master/ipr-gan-master/attack_dcgan.py", line 230, in <module>
    main()
  File "C:/Users/DELL/Downloads/ipr-gan-master/ipr-gan-master/attack_dcgan.py", line 147, in main
    generator_bef.load_state_dict(torch.load(os.path.join(args.path, 'checkpoint/generator.pt')))
  File "D:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

**Comment by dingsheng-ong** [comment]
Thank you for pointing that out. I notice that the `set_bitmask` in `train_dcgan.py` (line `186`) has been commented out, please uncomment it to include the white-box watermark training, then, re-run the attack scripts using the new checkpoints created. I apologize for the unorganized code, we are refactoring the code and will publish the latest version very soon.
